name: ocetrac-scipy-2021
channels:
  - conda-forge
dependencies:
  - jupyterlab=3
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-image
  - scipy
  - xarray
  - dask
  - matplotlib
  - cartopy
  - ipykernel
  - s3fs
  - zarr
  - ocetrac